### ISSUE TITLE
RuntimeWarning: invalid value encountered in true_divide

### ISSUE THREAD

**Issue by jcjlin** [marco-rudolph/AST#17]
Hi,

Firstly, I would like to extend my gratitude for your remarkable work on this project. It's truly impressive and has been very helpful.
I recently encountered an issue while running the preprocess.py script and hoped you might be able to provide some guidance. The following runtime warnings were triggered:

preprocess.py:32: RuntimeWarning: invalid value encountered in true_divide
Code: upper_left = np.sum(img[:2, :2]) / np.sum(img[:2, :2] > 0)

preprocess.py:33: RuntimeWarning: invalid value encountered in true_divide
Code: upper_right = np.sum(img[-2:, :2]) / np.sum(img[-2:, :2] > 0)

preprocess.py:34: RuntimeWarning: invalid value encountered in true_divide
Code: lower_left = np.sum(img[:2, -2:]) / np.sum(img[:2, -2:] > 0)

preprocess.py:35: RuntimeWarning: invalid value encountered in true_divide
Code: lower_right = np.sum(img[-2:, -2:]) / np.sum(img[-2:, -2:] > 0)

These warnings seem to suggest an issue with dividing by zero or encountering an invalid value. I'm unsure how to resolve this and would greatly appreciate any advice or guidance you could offer.

Thank you very much for your time and assistance.

**Comment by marco-rudolph** [comment]
Hi,

The code provides a minimal solution to compute a background plane that works for the MVTec 3DAD dataset. Since we do not focus on this part of the pipeline, it is not well optimized to deal with missing data. A more elegant solution would be to sample points at the image boundary and do a linear regression. You'd have to do something like this

`A = np.column_stack([x, y, np.ones(len(x))])`
`coefficients, residuals, rank, s = np.linalg.lstsq(A, z, rcond=None)`.

where x, y, z are 1D arrays of the 3D points at the image boundary (use only valid/non-zero pixels) and

`
a, b, d = coefficients`

in the plane z = ax + by + d. Depending on the noise and precision requirements, this can be fine-tuned arbitrarily.

Best,
Marco
