### ISSUE TITLE
NF problem

### ISSUE THREAD

**Issue by 0belle** [marco-rudolph/AST#7]
Whether can add a normal vector？maybe it has better result?
And maybe normalization flow can used in point cloud directly?

**Comment by marco-rudolph** [comment]
Hello,

we experimented with many representations of the depth image (also normals) but could not observe any improvement.

We also considered using the point cloud directly. Short tests gave no promising results using PointNet-like internal networks. Since the point cloud can be rasterized as a standard image, we hypothesize that using this structure with convolutional kernels makes more sense. 

But I don't want to rule out the possibility that these ideas could still work well. Often the result is strongly influenced by small details.

**Comment by 0belle** [comment]
Hello,
May I get your email? I think I need your help with some problems. Maybe its so ridiculous..

**Comment by marco-rudolph** [comment]
Hello,

my e-mail can be found on the paper. I'm open to questions that are directly related to the paper code.

Best,
Marco
